### ISSUE TITLE
broken dependency chain on master branch due to conflict on os-client-config dependency

### ISSUE THREAD

**Issue by ssbarnea** [rhos-infra/InfraRed#276]
If you install infrared from master branch you will have a broken installation:
```
pip check
openstacksdk 0.9.11 has requirement os-client-config>=1.22.0, but you have os-client-config 1.13.1.
```

This bug needs to be solved ASAP because the installed infrared will not work at all, giving this:
```
ir-provisioner
Traceback (most recent call last):
  File "/usr/bin/ir-provisioner", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2958, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2944, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2971, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (os-client-config 1.13.1 (/usr/lib/python2.7/site-packages), Requirement.parse('os-client-config>=1.22.0'), set(['openstacksdk']))
```

Also, in order to avoid such problem in the future the minimal set of test run on each changeset should include the execution of `pip check` after the installation of the package. If any conflict is found the build should be marked as failed. `pip check` was added recently on `pip>=9.0` and it should be used only as a test dependency.

**Comment by ssbarnea** [comment]
In order to prove this bug I created a branch that enables Travis builds on my fork. Here is the execution result https://travis-ci.org/ssbarnea/InfraRed/jobs/185258476

**Comment by yfried-redhat** [comment]
Hi Sorin,
This requirement has been removed a while ago. You should pull latest code (master or stable) from git and run "pip install -U ..." to update your local installation.

We are testing pip installation on the gate for every patch.

I'm closing this issue. If you are sure you have latest version installed (``pip list | grep "infrared"``) feel free to reopen it.
